### ISSUE TITLE
Peut être une erreur

### ISSUE THREAD

**Issue by apoque** [curquiza/curqui_test#4]
Bonjour je pense qu'il y a peut être une erreur au conv_bigs/bigs_precision_07;
printf("%.2ls", str) avec (wchar_t *)str tel que :
- str[0] = 'S';
- str[1] = 254;
- str[2] = 'u';
- str[3] = '\0';
le test imprime 'S˛' et renvoie 2, or 'S' prend 1 byte et '˛' en prend 2, du coup, selon moi printf ne devrait imprimer 'S' et renvoyer 1 non ?
Je me trompe peut être aussi :)
En tout cas merci pour la batterie de test !

**Comment by curquiza** [comment]
Hello ! Merci pour ton retour, et excuse moi pour le temps de réponse un peu tardif.
Oui ton raisonnement est tout à fait bon, mais uniquement dans le cas où on fait un `setlocale` ;) Ce qui n'est pas le cas dans ce test.
`str[0]` est donc sur 1 octet et `str[1]` aussi.
